### ISSUE TITLE
seq2seq dataset

### ISSUE THREAD

**Issue by Fije** [freesunshine0316/semantic-nmt#2]
Hi,
I was wondering, does the seq2seq folder provided on your repo contain the files used to retrieve your paper's seq2seq results? I was hoping to do some baseline experiments. I'm asking because the NP2P_data_stream.py file seems to read data for a Question-Answering task. Many thanks in advance.

**Comment by freesunshine0316** [comment]
Hi, 
The codes are originally developed for a QA task, but it's been adapted to MT. Actually [read_all_GenerationDatasets](https://github.com/freesunshine0316/semantic-nmt/blob/master/seq_to_seq/NP2P_data_stream.py#L50) is in use, and it's guaranteed by [this](https://github.com/freesunshine0316/semantic-nmt/blob/master/seq_to_seq/NP2P_trainer.py#L320)

**Comment by Fije** [comment]
Ahaaa, I see. Thank you!

**Comment by Fije** [comment]
Hi @freesunshine0316 , 

Reading your paper, I don't think I can find much about parameter settings for you seq2seq baseline. Can  I assume they were roughly the same as in Dual2Seq?

If I run both with roughly the same dimension settings in the config files, it seems like Dual2Seq is much larger than Seq2Seq. 

- Do you think we can hold the graph encoder part accountable for this, or do you think it might be of the context layer difference et cetera as well? 
- How did you make sure that you had roughly the same number parameters as Dual2Seq? 

Thank you, 
Fije

**Comment by freesunshine0316** [comment]
* Do you think we can hold the graph encoder part accountable for this, or do you think it might be of the context layer difference et cetera as well?
The core reason could be the graph encoder, but I'm not 100\% sure.

* How did you make sure that you had roughly the same number parameters as Dual2Seq?
We have other baselines that take the same number of parameters as the Dual2seq, such as Dual2seq-Dep, Dual2seq-SRL... etc.
